spring:
  datasource:
    url: jdbc:mysql://192.168.56.123:3306/flowable-spring-boot?characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123456
flowable:
  #关闭定时任务JOB
  async-executor-activate: false
