apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: httpserver-route-front
spec:
  http:
  - name: rule1
    match:
      hosts:
      - ai.com
      paths:
      - "/front/*"
    backends:
    - serviceName: front
      servicePort: 80
