
apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    run: consumer
#  annotations:
#    prometheus.io/port: "8481"
#    prometheus.io/spring: "true"
#    prometheus.io/path: "/api/actuator/prometheus"
spec:
  ports:
  - port: 8482
    protocol: TCP
  selector:
    run: consumer

