apiVersion: v1
kind: Service
metadata:
  name: nacos-prod
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8848
    name: a
    targetPort: 8848
    protocol: TCP
  - port: 9848
    targetPort: 9848
    protocol: TCP
    name: b
