# MySQL8配置
spring:
  datasource:
    # url: jdbc:p6spy:mysql://114.115.222.81:3307/aisong?useUnicode=true&useSSL=false&characterEncoding=UTF-8&characterSetResults=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    url: jdbc:p6spy:mysql://192.168.8.135:3306/aisong?useUnicode=true&useSSL=false&characterEncoding=UTF-8&characterSetResults=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: root
  redis:
    host: 192.168.8.135
    database: 10
    timeout: 1800000
    jedis:
      pool:
        max-wait: -1
        max-idle: 5
        min-idle: 0
# 配置日志输出 使用默认控制台打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations:
      - classpath:mapper/*.xml

global-config:
  db-config:
    logic-delete-value: 1
    logic-not-delete-value: 0
logging:
  config: classpath:logback-spring.xml


