
# MySQL8配置
spring:
  datasource:
    url: jdbc:p6spy:mysql://114.115.222.81:3307/aisong?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: wuyaming




# 配置日志输出 使用默认控制台打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    # 配置逻辑删除
global-config:
  db-config:
    logic-delete-value: 1
    logic-not-delete-value: 0